# Generated by Django 2.2.6 on 2019-12-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodUp', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='com',
            new_name='comment',
        ),
    ]
