# Generated by Django 2.2.6 on 2019-12-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodUp', '0003_auto_20191217_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='com',
        ),
    ]
