# Generated by Django 2.2.6 on 2019-11-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodUp', '0005_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='time_closed',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='time_opened',
            field=models.TimeField(null=True),
        ),
    ]
