# Generated by Django 2.2.6 on 2019-11-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodUp', '0006_auto_20191109_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
