# Generated by Django 2.2.6 on 2019-11-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodUp', '0007_auto_20191109_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
