# Generated by Django 2.2.6 on 2019-11-16 17:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dana',
            new_name='adres',
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_closed',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_opened',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('pizza', 'pizza'), ('beer', 'beer'), ('pasta', 'pasta'), ('burger', 'burger')], default=None, max_length=23),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(),
        ),
    ]
