# Generated by Django 2.2.6 on 2019-12-17 18:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191120_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('pizza', 'pizza'), ('beer', 'beer'), ('pasta', 'pasta'), ('burger', 'burger'), ('cake', 'cake'), ('chinese', 'chinese'), ('soup', 'soup'), ('pancakes', 'pancakes'), ('dumplings', 'dumplings')], default=None, max_length=60),
        ),
    ]
